name: 'Publish browser-agent/collection to npm'

on:
  push:
    branches: [main]

jobs:
  publish:
    name: Publish browser-agent
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org
    - name: Set correct yarn
      run: corepack enable
    - name: Install
      run: yarn
    - name: Build
      run: yarn build
    - name: Test
      run: yarn build:test
    - name: Publish
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
