name: 'Pull Request browser-id test'

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set correct yarn
      - run: corepack enable
      - name: Test
      - run: yarn test
